version: '3'
services:
  bq-gateway-01:
    #配置容器名
    container_name: biuqu-gateway-01
    # 指定镜像名
    image: biuqu/bq-gateway:1.1
    ports:
      # 暴露端口
      - "9992:9992"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/01:/opt/apps/bq-clusters/logs/
  bq-gateway-02:
    #配置容器名
    container_name: biuqu-gateway-02
    # 指定镜像名
    image: biuqu/bq-gateway:1.2
    ports:
      # 暴露端口
      - "9982:9982"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/02:/opt/apps/bq-clusters/logs/
  bq-gateway-03:
    #配置容器名
    container_name: biuqu-gateway-03
    # 指定镜像名
    image: biuqu/bq-gateway:1.3
    ports:
      # 暴露端口
      - "9972:9972"
    volumes:
      # 创建容器数据卷
      - ~/docker/bq-clusters/logs/03:/opt/apps/bq-clusters/logs/